{{- $namespace := .Release.Namespace | quote }}
{{- $fullname := include "container-agent.fullname" . }}

{{- if and .Values.rbac.create .Values.agent.autodetectPlatform }}
{{- $name := printf "%s-%s" $fullname "default" }}
{{- $serviceAccountName := include "container-agent.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}

{{- range $clusterRole := .Values.rbac.clusterRoles }}
{{- if $clusterRole.rules }}
{{- $name := join "-" (compact (list $fullname $clusterRole.name )) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
{{ toYaml $clusterRole.rules | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
