{{- $namespace := .Release.Namespace | quote }}
{{- $fullname := include "container-agent.fullname" . }}

{{- if .Values.rbac.create }}
{{- $name := printf "%s-%s" $fullname "default" }}
{{- $serviceAccountName := include "container-agent.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["", "events.k8s.io/v1"]
    resources: ["events"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}

{{- range $role := .Values.rbac.roles }}
{{- if $role.rules }}
{{- $name := join "-" (compact (list $fullname $role.name )) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $role.namespace | default $namespace }}
rules:
{{ toYaml $role.rules | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $role.namespace | default $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.logging.rbac.create }}
{{- $name := printf "%s-%s" $fullname .Values.logging.rbac.role.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["watch"]
{{- if .Values.logging.rbac.role.rules }}
  {{- toYaml .Values.logging.rbac.role.rules | indent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "container-agent.logging.serviceAccountName" . }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
{{- end }}
