resourceClass: dabs-dev-env

externalSecrets:
  data:
  - key: dev/dbt/snowflake
    name: DBT_AIRFLOW_USER_PRIVATE_KEY_PASS
    property: DBT_AIRFLOW_USER_PRIVATE_KEY_PASS
  - key: dev/dbt/snowflake
    name: SNOWFLAKE_PRIVATE_KEY_BASE64
    property: DBT_AIRFLOW_USER_PRIVATE_KEY_BASE64