apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circleci-runner.fullname" . }}
  labels:
    {{- include "circleci-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "circleci-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "circleci-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: circleci-runner
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "CIRCLECI_RESOURCE_CLASS"
              valueFrom:
                secretKeyRef:
                  key: resourceClass
                  name: {{ .Values.configSecret.name }}
            - name: "CIRCLECI_API_TOKEN"
              valueFrom:
                secretKeyRef:
                  key: runnerToken
                  name: {{ .Values.configSecret.name }}
            {{- if .Values.agentVersion }}
            - name: "agent_version"
              value: "{{ .Values.agentVersion }}"
            {{- end }}
            {{- range $k, $v := .Values.launchAgentEnvironmentVariables }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
            {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps -ef | grep circleci-launch-agent
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
