{{- if .Values.externalSecrets -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: secretsManager
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
