{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecret.name }}
data:
  resourceClass: {{ .Values.resourceClass | b64enc }}
  runnerToken: {{ .Values.runnerToken | b64enc }}
{{- end }} 
